apiVersion: apps/v1
kind: Deployment
metadata:
  name: always-encrypted-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: always-encrypted-sample
  template:
    metadata:
      labels:
        app: always-encrypted-sample
    spec:
      serviceAccountName: aks-keyvault-sa # Ensure this service account is bound to a managed identity with Key Vault access
      containers:
        - name: always-encrypted-sample
          image: kpantos/com.example.alwaysencrypted:v1
          env:
            - name: SQL_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: sql-conn-secret
                  key: connection-string
            - name: AZURE_MANAGED_IDENTITY_CLIENT_ID
              value: c79f5e7a-fefc-4e5e-98f6-3440bd2e9277
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-keyvault-sa
  annotations:
    azure.workload.identity/client-id: c79f5e7a-fefc-4e5e-98f6-3440bd2e9277 # Replace with your managed identity client ID
    azure.workload.identity/tenant-id: f129bc3c-3fb2-4d3b-85c8-839e1a9bd9e2 # Replace with your Azure tenant ID
    azure.workload.identity/service-account-token-expiration: "3600"
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-conn-secret
stringData:
  connection-string: "jdbc:sqlserver://UAPSQLServer;database=WideWorldImporters;user=sqltest@UAPSQLServer;password=StrongPassword123!;encrypt=true;"
