apiVersion: apps/v1
kind: Deployment
metadata:
  name: always-encrypted-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: always-encrypted-sample
  template:
    metadata:
      labels:
        app: always-encrypted-sample
    spec:
      serviceAccountName: aks-keyvault-sa # Ensure this service account is bound to a managed identity with Key Vault access
      containers:
        - name: always-encrypted-sample
          image: kpantos/com.example.alwaysencrypted:v1
          env:
            - name: SQL_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: sql-conn-secret
                  key: connection-string
            - name: AZURE_MANAGED_IDENTITY_CLIENT_ID
              value: 0636a8d3-87d1-4d44-8731-c0b07ef7d616

---
apiVersion: v1
kind: Secret
metadata:
  name: sql-conn-secret
stringData:
  connection-string: "jdbc:sqlserver://UAPSQLServer;database=WideWorldImporters;user=sqltest@UAPSQLServer;password=StrongPassword123!;encrypt=true;"
